version: '3'

services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
  ts-node:
    depends_on:
      - redis
    container_name: ts-node
    build: .
    command: sh -c "npm i && npm run start-dev"
    ports:
      - 8080:8080/tcp
    environment:
      REDIS_HOST: 'redis'
    volumes:
      - '.:/usr/app/'
    restart: unless-stopped
